### ISSUE TITLE
Unresolved references to deps libraries

### ISSUE THREAD

**Issue by sgara** [kmaragon/conan-aws-sdk-cpp#4]
Hi there,
Thanks for creating this conan package! 
Unfortunately, I have an issue while using it in a simple project related to AWS Lambda. The whole compilation works just fine, but at link step I have the following errors (output reduced for visibility):
```
/home/conan/.conan/data/aws-sdk-cpp/1.7.7/kmaragon/stable/package/76b466be5a747d7a8416bace65ef0fd7af6a3bb1/lib/libaws-cpp-sdk-core.a(EventStreamDecoder.cpp.o): In function `Aws::Utils::Event::EventStreamDecoder::EventStreamDecoder(Aws::Utils::Event::EventStreamHandler*)':
EventStreamDecoder.cpp:(.text+0x964): undefined reference to `aws_default_allocator'
EventStreamDecoder.cpp:(.text+0x990): undefined reference to `aws_event_stream_streaming_decoder_init'
[...]
collect2: error: ld returned 1 exit status
``` 

I'm using this conf for aws-cpp-sdk recipe:
```
aws-sdk-cpp:shared=False
aws-sdk-cpp:build_s3=True
aws-sdk-cpp:build_sqs=True
```

From what I found so far, it seems that aws-cpp-sdk depends on `aws-c-common`, `aws-c-event-stream` and `aws-checksums`. Their CMake project do install them and I can see them on `conan install` output, but I'm guessing that those are not included in conan recipe and thus `target_link_libraries(${PROJECT_NAME} ${CONAN_LIBS})` doesn't work as expected. 
Do I need to add a manual conf so that those libraries are linked to my project? 
Should there be something added to this package conf to export them automatically? 
Should we create recipes for those 3 dependencies and turn `BUILD_DEPS` off in aws-sdk build?

**Comment by kmaragon** [comment]
Doh! That's right! I meant to fix this weeks ago and forgot before being buried by my day (and night, midnight, and weekend) day job. Those libraries are built by the package, but they aren't added to the libs in the package info function. I had it fixed locally and accidentally clobbered the fix. The important thing with that is that the libs need to be ordered correctly for static linkage.

**Comment by Malacath92** [comment]
Good to know it's not just us  with this issue  :)

When should we expect a fix?
Or is there a manual workaround that we are missing?

**Comment by kmaragon** [comment]
So adding those to the link should have worked. 

But if you are doing static linkage, you will need to switch stream and common. When linking with static libraries, the order matters. With dynamic linkage, the addresses are resolved on library load (dynamic). But with static linkage, they are resolved at compile time. So the order is important. As symbols are resolved, they are picked out of the static libraries that come *after* the library. aws-c-event-stream depends on both aws-c-common and aws-checksums. So the latter two need to come *after* aws-c-event-stream. Conversely, all of the aws modules depend on aws-cpp-sdk-core so that one always came last (but now AWS added those 3 new dependencies from aws-cpp-sdk-core itself).  I think I remember seeing that aws-c-common also depends on aws-checksums. So that also needs to be ordered as such. 

In any event, 1.7.64 should be up for Linux... it's still building for Windows at the time of this comment (AppVeyor is really really really slow). These will have these added, in the correct order (I think).

**Comment by kmaragon** [comment]
ok never mind - no Linux build - the 32 bit build is failing on these libraries specifically - they may not support cross compilation

**Comment by kmaragon** [comment]
It looks like the fix in https://github.com/aws/aws-sdk-cpp/commit/312db5e6940e67e81bda38edd09eeee7e0316899 may have had some pieces that should have made it into the non OSX / Android case.

In https://github.com/aws/aws-sdk-cpp/blob/master/third-party/cmake/BuildAwsCCommon.cmake#L39
and https://github.com/aws/aws-sdk-cpp/blob/master/third-party/cmake/BuildAwsChecksums.cmake#L38
and https://github.com/aws/aws-sdk-cpp/blob/master/third-party/cmake/BuildAwsEventStream.cmake#L45

It looks like the cmake variables that are telling cmake to build a 32 bit binary are not being forwarded to the external projects so aws-sdk-cpp is building 64 bit libraries of these 3 requirements to then be linked to 32 bit everything else. I will need to open an issue / PR with aws-sdk-cpp or create a patch to fix this that is applied in the conan build :cry:

**Comment by kmaragon** [comment]
Or I could just stop shipping 32 bit binaries... anyone using this package for 32 bit builds?

**Comment by kmaragon** [comment]
In the meantime, I opened https://github.com/aws/aws-sdk-cpp/issues/1086

**Comment by sgara** [comment]
Thanks for the fix, I’ll try ASAP!
I’m not using 32bit binaries, my sole purpose was to build for AWS Lambda with C++ runtime :)
And it seems that I’m not there yet but that’s another story

**Comment by WolfgangVogl** [comment]
> Or I could just stop shipping 32 bit binaries... anyone using this package for 32 bit builds?
Yes, I'm using it for 32bit builds on Windows.

**Comment by kmaragon** [comment]
Ok @WolfgangVogl I will keep trying to debug the aws-sdk-cpp build for x86 from an x86_64 machine on Windows. I have a branch of the main aws-sdk-cpp repo with the fixes to the upstream code based on the patch that is now in this package repo to get it to work on Linux. Presumably I'll be able to update the patch to fix whatever else is going on.

Ultimately this is because of the way that aws-sdk-cpp git pulls and builds the aws-c-* libraries. Rather than building them as *part of* the CMake build of the main library, the cmake build forks off a child process to build them. The child process just throws away most of the build setup that conan sets up for cross compilation (including MSVCRT flags on Windows). So then when it tries to link these libraries, it can't because the aws-c-* libs are all native to the machine they were built on - i.e. x86_64 on  a 64 bit machine that is cross compiling for a 32 tbit machine.

I need to patch aws-sdk-cpp so that when it launches the child cmake it carries the pertinent CMAKE_* flags into the child process. So far I'm only carrying C_FLAGS and CXX_FLAGS in the patch. For the Windows build, I'm missing something as it's still linking the aws-c-* libs against a different MSVCRT than the main cpp libs.

**Comment by kmaragon** [comment]
At this point, I am left having to assume that something somewhere in the aws-c-* libs, the runtime library is being overwritten. I ensured that it's getting carried through (as /MT since I was doing static builds) in the CMAKE_C_FLAGS but it still got changed to /MD. So I am left having to assume that these libraries not only don't handle the runtime, but actively *undo* it. This will be a problem for any static Windows builds.

I did see, however, that this commit went in fairly recently: 
https://github.com/awslabs/aws-c-common/blob/8e36c092bd103272a7162026dafea136d151617f/cmake/AwsCFlags.cmake#L125
But the 1.7.64 release is pegged to commitf 5383755e934745811d777a8e6c6866791b4302e

**Comment by kmaragon** [comment]
https://github.com/aws/aws-sdk-cpp/pull/1087 is opened so the next release can remove the current patches. I'm about to throw in the towel on static windows builds. @WolfgangVogl you should already be able to build (with shared=True only) as it is for both x86 and x86_64. But I can't confirm that because the appveyor build fails to more broken interaction between aws-c-* and aws-sdk-cpp. I'm throwing in the towel on that one and will EXTREMELY happily accept a pull request for the Windows /MD /MT issue between aws-sdk-cpp and aws-c-*. But in reality, that fix will need to go into those repos. But someone probably needs to open a PR to do that. Preferably someone who has a Windows machine they can try to fix it with. God knows that'll be a lot quicker than waiting for what feels like 66MHz AppVeyor build agents with 4MB of memory. With that, I'm going to close this issue. But anyone reading this - please help me fix windows /MT builds (which has nothing to do with the original issue).

**Comment by WolfgangVogl** [comment]
I'm totally lost what's going wrong with the aws cpp sdk cmake files...
- I'm building on a Windows 64bit machine for a 32bit static linked project
- Until now I've created debug builds for testing but now I tried to change to release... FAIL

=> Is it https://github.com/aws/aws-sdk-cpp/issues/1039?

aws-c-event-stream.lib(event_stream.obj) : error LNK2001: unresolved external symbol __imp___wassert
aws-c-common.lib(error.obj) : error LNK2001: unresolved external symbol __imp___wassert
aws-c-common.lib(array_list.obj) : error LNK2001: unresolved external symbol __imp___wassert
aws-c-common.lib(encoding.obj) : error LNK2001: unresolved external symbol __imp___wassert

Would be nice if you can give me a helping hand how to proceed with this issue... @kmaragon 
=> Checkout the aws c++ sdk git repo and start modifying cmake files?
